package com.bashar.physicianschedule.core

import java.time.DayOfWeek
import java.time.LocalDate
import java.time.temporal.ChronoUnit
import java.time.temporal.TemporalAdjusters

object RecurrenceEngine {

    /** Dates generated by [rule] that fall within [from]..[to] (inclusive), in order. */
    fun occurrenceDates(rule: Recurrence, from: LocalDate, to: LocalDate): List<LocalDate> {
        if (to.isBefore(from)) return emptyList()
        val last = listOfNotNull(to, rule.endDate).min()
        // With a count limit every occurrence from the start must be counted, so no skipping ahead.
        val seq = generate(rule, skipTo = if (rule.count == null) from else null)
            .takeWhile { !it.isAfter(last) }
        val limited = if (rule.count != null) seq.take(rule.count.coerceAtLeast(0)) else seq
        return limited.filter { !it.isBefore(from) }.toList()
    }

    /** The last date the series produces, or null when it never ends. */
    fun lastOccurrence(rule: Recurrence): LocalDate? {
        if (rule.count == null && rule.endDate == null) return null
        val seq = generate(rule, null)
        val bounded = if (rule.endDate != null) seq.takeWhile { !it.isAfter(rule.endDate) } else seq
        val limited = if (rule.count != null) bounded.take(rule.count.coerceAtLeast(0)) else bounded
        return limited.lastOrNull()
    }

    /** Number of occurrences strictly before [date]. */
    fun countBefore(rule: Recurrence, date: LocalDate): Int {
        val seq = generate(rule, null).takeWhile { it.isBefore(date) }
        val bounded = if (rule.endDate != null) seq.takeWhile { !it.isAfter(rule.endDate) } else seq
        val limited = if (rule.count != null) bounded.take(rule.count) else bounded
        return limited.count()
    }

    /** The occurrence immediately before [date], if any. */
    fun previousOccurrence(rule: Recurrence, date: LocalDate): LocalDate? {
        val seq = generate(rule, null).takeWhile { it.isBefore(date) }
        val bounded = if (rule.endDate != null) seq.takeWhile { !it.isAfter(rule.endDate) } else seq
        val limited = if (rule.count != null) bounded.take(rule.count) else bounded
        return limited.lastOrNull()
    }

    fun isOccurrence(rule: Recurrence, date: LocalDate): Boolean =
        occurrenceDates(rule, date, date).isNotEmpty()

    private fun generate(rule: Recurrence, skipTo: LocalDate?): Sequence<LocalDate> {
        val interval = rule.interval.coerceAtLeast(1).toLong()
        val start = rule.startDate
        return when (rule.frequency) {
            Frequency.DAILY -> {
                val k0 = if (skipTo != null && skipTo.isAfter(start)) ChronoUnit.DAYS.between(start, skipTo) / interval else 0L
                generateSequence(k0) { it + 1 }.map { start.plusDays(it * interval) }
            }
            Frequency.WEEKLY -> {
                val days = rule.daysOfWeek.ifEmpty { setOf(start.dayOfWeek) }.sortedBy { it.value }
                val week0 = start.with(TemporalAdjusters.previousOrSame(DayOfWeek.MONDAY))
                val w0 = if (skipTo != null && skipTo.isAfter(start)) {
                    ChronoUnit.WEEKS.between(week0, skipTo.with(TemporalAdjusters.previousOrSame(DayOfWeek.MONDAY))) / interval
                } else 0L
                generateSequence(w0) { it + 1 }.flatMap { w ->
                    val weekStart = week0.plusWeeks(w * interval)
                    days.asSequence().map { weekStart.plusDays((it.value - 1).toLong()) }
                }.filter { !it.isBefore(start) }
            }
            Frequency.MONTHLY -> {
                val dom = start.dayOfMonth
                val m0 = if (skipTo != null && skipTo.isAfter(start)) {
                    ChronoUnit.MONTHS.between(start.withDayOfMonth(1), skipTo.withDayOfMonth(1)) / interval
                } else 0L
                // Stop eventually even if the day never exists again (cannot happen for dom <= 31,
                // but guards against an unbounded scan when every candidate is skipped).
                generateSequence(m0) { it + 1 }.take(100_000)
                    .map { start.plusMonths(it * interval) }
                    .filter { it.dayOfMonth == dom }
            }
        }
    }
}
