#!/usr/bin/env bash
# Rebuilds bashar_ai_knowledge.md from the module, routing and output files.
# Run after editing anything in ../modules or ../central.
set -euo pipefail
cd "$(dirname "$0")"
out=bashar_ai_knowledge.md
{
  echo "# Bashar AI — Knowledge: Specialist Modes"
  echo
  echo "_Generated by build_knowledge.sh from bashar_ai/modules and bashar_ai/central. Edit those files, not this one._"
  for m in medical research teaching personal administrative technology web_research document; do
    echo; echo "---"; echo
    sed 's#`\.\./policies/\([a-z_]*\)\.md`#the Project instructions#g' "../modules/$m.md"
  done
  echo; echo "---"; echo
  echo "# Routing guide (intent signals → mode)"
  echo; echo '```yaml'; cat ../central/routing.yaml; echo '```'
  echo; echo "---"; echo
  cat ../central/unified_output.md
} > "$out"
echo "wrote $out"
