// General-paediatrics catalogue: investigation sections with common tests (and the unit most labs
// report them in, used only to pre-fill an empty unit box), clinical features grouped by system,
// and common presenting complaints. Everything stays free text: any test/unit/feature can be typed.

export const INV_CATS = {
  "Hematology": [["Hemoglobin (Hb)", "g/dL"], ["Hematocrit", "%"], ["RBC", "×10¹²/L"], ["MCV", "fL"], ["MCH", "pg"], ["RDW", "%"], ["WBC", "×10⁹/L"], ["Neutrophils", "×10⁹/L"], ["Lymphocytes", "×10⁹/L"], ["Eosinophils", "×10⁹/L"], ["Platelets", "×10⁹/L"], ["Reticulocytes", "%"], ["Blood film", ""], ["Hb electrophoresis", ""], ["G6PD", ""], ["Direct Coombs test", ""], ["Blood group", ""]],
  "Coagulation": [["PT", "s"], ["INR", ""], ["aPTT", "s"], ["Fibrinogen", "g/L"], ["D-dimer", "mg/L FEU"], ["Factor VIII", "%"], ["Factor IX", "%"], ["von Willebrand antigen", "%"], ["Bleeding time", "min"]],
  "Biochemistry": [["Sodium", "mmol/L"], ["Potassium", "mmol/L"], ["Chloride", "mmol/L"], ["Bicarbonate", "mmol/L"], ["Urea", "mmol/L"], ["Creatinine", "µmol/L"], ["eGFR", "mL/min/1.73m²"], ["Glucose", "mmol/L"], ["Calcium", "mmol/L"], ["Ionized calcium", "mmol/L"], ["Phosphate", "mmol/L"], ["Magnesium", "mmol/L"], ["Alkaline phosphatase", "U/L"], ["Uric acid", "µmol/L"], ["Ammonia", "µmol/L"], ["Lactate", "mmol/L"], ["CK", "U/L"], ["LDH", "U/L"], ["Osmolality (serum)", "mOsm/kg"]],
  "Liver": [["ALT", "U/L"], ["AST", "U/L"], ["GGT", "U/L"], ["Total bilirubin", "µmol/L"], ["Direct bilirubin", "µmol/L"], ["Albumin", "g/L"], ["Total protein", "g/L"], ["Bile acids", "µmol/L"]],
  "Blood gas": [["pH", ""], ["pCO₂", "kPa"], ["pO₂", "kPa"], ["HCO₃", "mmol/L"], ["Base excess", "mmol/L"], ["Lactate", "mmol/L"], ["Anion gap", "mmol/L"]],
  "Infection / inflammation": [["CRP", "mg/L"], ["ESR", "mm/h"], ["Procalcitonin", "ng/mL"], ["Blood culture", ""], ["Urine culture", ""], ["CSF analysis & culture", ""], ["Throat swab", ""], ["Respiratory viral PCR panel", ""], ["Stool culture", ""], ["Malaria film / RDT", ""], ["Wound / pus culture", ""]],
  "Serology / virology": [["HBsAg", ""], ["Anti-HBs", "mIU/mL"], ["Anti-HCV", ""], ["HIV Ag/Ab", ""], ["CMV IgM / IgG", ""], ["EBV serology", ""], ["Toxoplasma IgM / IgG", ""], ["Rubella IgG", ""], ["Measles IgG", ""], ["Brucella serology", ""], ["Typhoid (Widal / culture)", ""], ["Mantoux / IGRA (TB)", ""], ["ASO titre", "IU/mL"], ["Mycoplasma serology", ""]],
  "Immunology / allergy": [["IgG", "g/L"], ["IgA", "g/L"], ["IgM", "g/L"], ["Total IgE", "kU/L"], ["Specific IgE", "kUA/L"], ["Skin prick test", ""], ["ANA", ""], ["Anti-dsDNA", "IU/mL"], ["C3", "g/L"], ["C4", "g/L"], ["Lymphocyte subsets (CD3/4/8/19/56)", ""], ["Vaccine antibody responses", ""]],
  "Nutrition / vitamins": [["Ferritin", "µg/L"], ["Serum iron", "µmol/L"], ["TIBC", "µmol/L"], ["Transferrin saturation", "%"], ["25-OH vitamin D", "nmol/L"], ["Vitamin B12", "pmol/L"], ["Folate", "nmol/L"], ["Zinc", "µmol/L"], ["Vitamin A", "µmol/L"], ["Prealbumin", "g/L"]],
  "Lipids": [["Total cholesterol", "mmol/L"], ["LDL cholesterol", "mmol/L"], ["HDL cholesterol", "mmol/L"], ["Triglycerides", "mmol/L"], ["Non-HDL cholesterol", "mmol/L"]],
  "Endocrine": [["TSH", "mIU/L"], ["Free T4", "pmol/L"], ["Free T3", "pmol/L"], ["IGF-1", "ng/mL"], ["IGFBP-3", "mg/L"], ["GH peak (stimulation test)", "ng/mL"], ["Cortisol (8 am)", "nmol/L"], ["ACTH", "pmol/L"], ["17-OH progesterone", "nmol/L"], ["LH", "IU/L"], ["FSH", "IU/L"], ["Testosterone", "nmol/L"], ["Estradiol", "pmol/L"], ["DHEAS", "µmol/L"], ["Prolactin", "mIU/L"], ["PTH", "pmol/L"], ["HbA1c", "%"], ["Insulin", "mIU/L"], ["C-peptide", "nmol/L"], ["Karyotype (DSD)", ""]],
  "Celiac / GI": [["tTG-IgA", "U/mL"], ["Total IgA", "g/L"], ["EMA", ""], ["Fecal calprotectin", "µg/g"], ["Fecal elastase", "µg/g"], ["Stool occult blood", ""], ["Stool ova & parasites", ""], ["H. pylori stool antigen", ""], ["Lipase", "U/L"], ["Amylase", "U/L"], ["Endoscopy / biopsy", ""]],
  "Urine": [["Urinalysis (dipstick)", ""], ["Urine microscopy", ""], ["Urine protein/creatinine ratio", "mg/mmol"], ["Urine albumin/creatinine ratio", "mg/mmol"], ["Urine calcium/creatinine ratio", "mmol/mmol"], ["Urine osmolality", "mOsm/kg"], ["Urine sodium", "mmol/L"], ["24-h urine protein", "mg/day"], ["Urine specific gravity", ""]],
  "Cardiology": [["ECG", ""], ["Echocardiography", ""], ["Troponin", "ng/L"], ["NT-proBNP", "pg/mL"], ["Holter monitoring", ""], ["Blood pressure (ABPM)", "mmHg"]],
  "Neurology / development": [["EEG", ""], ["CSF analysis", ""], ["Nerve conduction / EMG", ""], ["Hearing test (OAE / ABR / audiometry)", ""], ["Vision assessment", ""], ["Developmental assessment", ""], ["Cognitive / IQ assessment", ""]],
  "Pulmonary": [["Sweat chloride", "mmol/L"], ["Spirometry – FEV₁", "% predicted"], ["Spirometry – FVC", "% predicted"], ["Peak flow", "L/min"], ["Oxygen saturation", "%"], ["Sleep study (polysomnography)", ""]],
  "Metabolic / newborn screening": [["Newborn screening panel", ""], ["Plasma amino acids", ""], ["Urine organic acids", ""], ["Acylcarnitine profile", ""], ["Very long-chain fatty acids", ""], ["Urine reducing substances", ""], ["Galactosaemia screen (GALT)", ""]],
  "Bone age / X-ray": [["Bone age (Greulich–Pyle)", "years"], ["Bone age (TW3)", "years"], ["Chest X-ray", ""], ["Abdominal X-ray", ""], ["Skeletal survey", ""], ["Limb / joint X-ray", ""], ["Spine X-ray", ""]],
  "Imaging": [["Abdominal ultrasound", ""], ["Renal ultrasound", ""], ["Pelvic ultrasound", ""], ["Cranial ultrasound", ""], ["Hip ultrasound", ""], ["CT head", ""], ["CT chest / abdomen", ""], ["MRI brain / pituitary", ""], ["MRI spine", ""], ["VCUG / MCUG", ""], ["DMSA scan", ""], ["DEXA (bone density)", "Z-score"]],
  "Genetics": [["Karyotype", ""], ["Chromosomal microarray", ""], ["FISH", ""], ["Fragile X testing", ""], ["SHOX analysis", ""], ["Gene panel", ""], ["Whole exome / genome", ""]],
  "Toxicology / drug levels": [["Lead level", "µmol/L"], ["Paracetamol level", "mg/L"], ["Salicylate level", "mg/L"], ["Anti-epileptic drug level", ""], ["Gentamicin level", "mg/L"], ["Vancomycin level", "mg/L"], ["Urine drug screen", ""]],
  "Other": [],
};

export const unitFor = (test) => {
  const t = String(test || "").trim().toLowerCase();
  for (const list of Object.values(INV_CATS)) for (const [name, unit] of list) if (name.toLowerCase() === t) return unit;
  return "";
};

export const FEATURE_GROUPS = {
  "General": ["Fever", "Lethargy", "Irritability", "Weight loss", "Night sweats", "Lymphadenopathy", "Pallor", "Jaundice", "Dehydration", "Edema"],
  "Growth & nutrition": ["Short stature", "Tall stature", "Poor weight gain / failure to thrive", "Obesity", "Growth deceleration", "Feeding difficulties", "Picky eating"],
  "Respiratory / ENT": ["Cough", "Wheeze", "Shortness of breath", "Stridor", "Nasal congestion", "Sore throat", "Ear pain / discharge", "Snoring"],
  "Cardiovascular": ["Heart murmur", "Cyanosis", "Chest pain", "Palpitations", "Syncope", "Hypertension"],
  "Gastrointestinal": ["Vomiting", "Diarrhea", "Constipation", "Abdominal pain", "Abdominal distension", "Blood in stool", "Reflux", "Hepatosplenomegaly"],
  "Renal / urinary": ["Dysuria", "Frequency", "Enuresis", "Hematuria", "Proteinuria", "Oliguria"],
  "Neurology / development": ["Seizures", "Headache", "Developmental delay", "Regression", "Hypotonia", "Abnormal gait", "Macrocephaly", "Microcephaly", "Visual problems", "Hearing concern"],
  "Behaviour / mental health": ["ADHD features", "Autism features", "Sleep problems", "Anxiety", "Low mood", "School difficulties"],
  "Skin": ["Rash", "Eczema", "Urticaria", "Petechiae / purpura", "Café-au-lait spots", "Acanthosis nigricans"],
  "Musculoskeletal": ["Joint pain / swelling", "Limp", "Bone pain", "Scoliosis", "Disproportionate body segments"],
  "Endocrine / puberty": ["Early puberty", "Delayed puberty", "Goitre", "Polyuria / polydipsia", "Hirsutism", "Gynecomastia", "Ambiguous genitalia", "Undescended testes"],
  "Hematology / immunology": ["Bruising / bleeding", "Recurrent infections", "Anemia symptoms", "Allergy / anaphylaxis"],
  "Syndromic": ["Dysmorphic features", "Midline defects", "Congenital anomalies", "Family history of similar condition"],
};

export const COMPLAINTS = ["Fever", "Cough", "Difficulty breathing", "Wheeze", "Vomiting", "Diarrhea", "Constipation", "Abdominal pain", "Poor feeding", "Poor weight gain", "Short stature", "Tall stature", "Obesity", "Rash", "Seizure", "Headache", "Developmental delay", "Behavioural concern", "Jaundice", "Pallor / anemia", "Bruising / bleeding", "Joint pain / limp", "Urinary symptoms", "Bedwetting", "Ear pain", "Sore throat", "Early puberty", "Delayed puberty", "Recurrent infections", "Routine check-up / follow-up", "Vaccination visit"];

// General & specialist paediatric treatments by therapeutic area (generic / INN names only; the app
// never suggests doses — every dose is entered and checked by the clinician against a formulary).
export const TREATMENT_CATS = {
  "Analgesia / antipyretics": ["Paracetamol (acetaminophen)", "Ibuprofen", "Naproxen", "Diclofenac", "Ketorolac", "Metamizole (dipyrone)", "Codeine (not < 12 y)", "Tramadol", "Buprenorphine", "Morphine", "Oxycodone", "Fentanyl", "Lidocaine–prilocaine cream (EMLA)", "Sucrose 24% (neonatal analgesia)", "Diamorphine (incl. intranasal)"],
  "Antibiotics": ["Amoxicillin", "Co-amoxiclav (amoxicillin–clavulanate)", "Ampicillin", "Benzylpenicillin (penicillin G)", "Phenoxymethylpenicillin (penicillin V)", "Benzathine penicillin", "Flucloxacillin / cloxacillin", "Piperacillin–tazobactam", "Cefalexin", "Cefadroxil", "Cefuroxime", "Cefixime", "Cefdinir", "Cefotaxime", "Ceftriaxone", "Ceftazidime", "Cefepime", "Meropenem", "Imipenem–cilastatin", "Azithromycin", "Clarithromycin", "Erythromycin", "Gentamicin", "Amikacin", "Tobramycin", "Vancomycin", "Teicoplanin", "Linezolid", "Fidaxomicin", "Ceftaroline", "Tigecycline", "Cefiderocol", "Ceftolozane–tazobactam", "Polymyxin B", "Minocycline", "Daptomycin", "Aztreonam", "Clindamycin", "Metronidazole", "Trimethoprim–sulfamethoxazole (co-trimoxazole)", "Trimethoprim", "Nitrofurantoin", "Ciprofloxacin", "Levofloxacin", "Doxycycline (≥ 8 y)", "Rifampicin", "Colistin", "Fosfomycin", "Pivmecillinam", "Chloramphenicol (systemic)", "Mupirocin (topical)", "Wound dressings", "Fusidic acid (topical)"],
  "Antituberculous": ["Isoniazid", "Rifampicin", "Pyrazinamide", "Ethambutol", "Pyridoxine (with isoniazid)", "Rifapentine", "Cycloserine (MDR-TB)"],
  "Antivirals": ["Aciclovir", "Valaciclovir", "Famciclovir", "Ganciclovir", "Valganciclovir", "Oseltamivir", "Baloxavir marboxil", "Zanamivir", "Remdesivir", "Nirmatrelvir–ritonavir", "Tenofovir", "Entecavir", "Lamivudine", "Zidovudine", "Nevirapine", "Ritonavir", "Bictegravir–emtricitabine–tenofovir alafenamide", "Cabotegravir", "Doravirine", "Enfuvirtide", "Lenacapavir", "Efavirenz", "Emtricitabine", "Rilpivirine", "Darunavir", "Atazanavir", "Raltegravir", "Maraviroc", "Elvitegravir–cobicistat–emtricitabine–tenofovir alafenamide", "Ribavirin", "Dolutegravir", "Etravirine", "Abacavir", "Lopinavir–ritonavir", "Sofosbuvir-based regimen (HCV)", "Sofosbuvir–velpatasvir", "Glecaprevir–pibrentasvir", "Ledipasvir–sofosbuvir", "Palivizumab (RSV prophylaxis)", "Nirsevimab (RSV prophylaxis)"],
  "Antifungals / antiparasitics": ["Nystatin", "Miconazole oral gel", "Clotrimazole (topical)", "Fluconazole", "Itraconazole", "Voriconazole", "Posaconazole", "Isavuconazole", "Amphotericin B (liposomal)", "Amphotericin B (conventional)", "Caspofungin", "Micafungin", "Terbinafine", "Griseofulvin", "Albendazole", "Mebendazole", "Ivermectin", "Praziquantel", "Pyrantel", "Permethrin 5% (scabies)", "Artemether–lumefantrine", "Artesunate", "Quinine", "Chloroquine", "Proguanil", "Atovaquone–proguanil", "Primaquine", "Nitazoxanide", "Tinidazole", "Pentamidine", "Levamisole (roundworm)"],
  "Respiratory / asthma": ["Salbutamol (albuterol)", "Terbutaline", "Ipratropium bromide", "Budesonide (inhaled / nebulised)", "Fluticasone propionate (inhaled)", "Beclometasone (inhaled)", "Ciclesonide", "Budesonide–formoterol", "Fluticasone–salmeterol", "Salmeterol", "Formoterol", "Tiotropium", "Montelukast", "Prednisolone", "Dexamethasone (croup)", "Nebulised adrenaline (epinephrine)", "Magnesium sulfate (IV, severe asthma)", "Aminophylline", "Theophylline", "Hypertonic saline (nebulised)", "Dornase alfa", "Ivacaftor", "Lumacaftor–ivacaftor", "Tezacaftor–ivacaftor", "Tobramycin (inhaled)", "Levofloxacin (inhaled)", "Mannitol (inhaled, CF)", "Omalizumab", "Mepolizumab", "Dupilumab", "Caffeine citrate (apnoea of prematurity)", "Surfactant (poractant / beractant)", "Elexacaftor–tezacaftor–ivacaftor (CF)", "Pancreatic enzymes (pancrelipase)"],
  "Allergy / anaphylaxis": ["Adrenaline (epinephrine) auto-injector", "Adrenaline (epinephrine) IM", "Cetirizine", "Levocetirizine", "Loratadine", "Desloratadine", "Fexofenadine", "Chlorphenamine (chlorpheniramine)", "Diphenhydramine", "Hydroxyzine", "Mometasone nasal spray", "Fluticasone nasal spray", "Azelastine nasal spray", "Sodium cromoglicate", "Allergen immunotherapy (SLIT / SCIT)", "Oral immunotherapy (peanut)"],
  "Cardiology": ["Furosemide", "Spironolactone", "Hydrochlorothiazide", "Bumetanide", "Amiloride", "Eplerenone", "Minoxidil", "Phenoxybenzamine", "Phentolamine", "Nicardipine", "Sodium nitroprusside", "Torasemide", "Metolazone", "Chlorothiazide", "Captopril", "Enalapril", "Lisinopril", "Losartan", "Amlodipine", "Nifedipine", "Propranolol", "Atenolol", "Bisoprolol", "Carvedilol", "Metoprolol", "Labetalol", "Esmolol", "Hydralazine", "Digoxin", "Amiodarone", "Adenosine", "Flecainide", "Procainamide", "Quinidine", "Sotalol", "Milrinone", "Levosimendan", "Vasopressin", "Phenylephrine", "Dopamine", "Dobutamine", "Noradrenaline (norepinephrine)", "Alprostadil (prostaglandin E1)", "Indometacin (PDA)", "Ibuprofen IV (PDA)", "Sildenafil (pulmonary hypertension)", "Bosentan", "Ambrisentan", "Selexipag", "Iloprost (inhaled)", "Sacubitril–valsartan", "Macitentan", "Epoprostenol", "Treprostinil", "Midodrine", "Aspirin (Kawasaki / antiplatelet)", "Atorvastatin", "Ivabradine"],
  "Gastroenterology / hepatology": ["Omeprazole", "Esomeprazole", "Lansoprazole", "Pantoprazole", "Famotidine", "Ranitidine", "Sucralfate", "Domperidone", "Metoclopramide", "Prochlorperazine", "Promethazine", "Droperidol", "Cimetidine", "Erythromycin (prokinetic)", "Ondansetron", "Oral rehydration solution (ORS)", "Zinc sulfate (diarrhoea)", "Racecadotril", "Loperamide (not < 2 y)", "Lactulose", "Polyethylene glycol (macrogol)", "Senna", "Bisacodyl", "Glycerin suppository", "Sodium picosulfate", "Mineral oil (liquid paraffin)", "Simethicone", "Probiotic (e.g. L. reuteri, LGG)", "Mesalazine (5-ASA)", "Sulfasalazine", "Azathioprine", "Methotrexate", "Infliximab", "Adalimumab", "Budesonide (oral, IBD)", "Exclusive enteral nutrition (Crohn's)", "Ursodeoxycholic acid", "Teduglutide", "Linaclotide", "Prucalopride", "Cholestyramine", "Rifampicin (pruritus)", "Vitamin K (phytomenadione)", "Fat-soluble vitamins (ADEK)", "H. pylori triple therapy", "Octreotide", "Terlipressin", "Glucagon", "Hyoscine butylbromide", "Peppermint oil"],
  "Nephrology / urology": ["Prednisolone (nephrotic syndrome)", "Cyclophosphamide", "Ciclosporin", "Tacrolimus", "Mycophenolate mofetil", "Rituximab", "Levamisole", "Enalapril (proteinuria)", "Furosemide", "Albumin 20%", "Sodium bicarbonate", "Calcium carbonate (phosphate binder)", "Sevelamer", "Calcitriol", "Alfacalcidol", "Erythropoietin (epoetin / darbepoetin)", "Iron sucrose (IV)", "Potassium citrate", "Desmopressin (enuresis)", "Oxybutynin", "Tolterodine", "Trimethoprim (UTI prophylaxis)", "Nitrofurantoin (UTI prophylaxis)", "Cefalexin (UTI prophylaxis)", "Tamsulosin", "Eculizumab (aHUS)", "Ravulizumab", "Growth hormone (CKD)"],
  "Neurology / epilepsy": ["Levetiracetam", "Sodium valproate", "Carbamazepine", "Oxcarbazepine", "Eslicarbazepine", "Lamotrigine", "Topiramate", "Phenobarbital", "Phenytoin / fosphenytoin", "Ethosuximide", "Clobazam", "Clonazepam", "Lacosamide", "Pentobarbital", "Nimodipine", "Zonisamide", "Vigabatrin", "Rufinamide", "Perampanel", "Brivaracetam", "Stiripentol", "Cannabidiol", "Fenfluramine", "Prednisolone / ACTH (infantile spasms)", "Ketogenic diet", "Midazolam (buccal / intranasal)", "Diazepam (rectal / IV)", "Lorazepam", "Pyridoxine (B6-dependent epilepsy)", "Baclofen", "Baclofen (intrathecal)", "Botulinum toxin A", "Trihexyphenidyl", "Gabapentin", "Pregabalin", "Amitriptyline (headache / pain)", "Propranolol (migraine prophylaxis)", "Topiramate (migraine prophylaxis)", "Sumatriptan (nasal)", "Acetazolamide", "Nusinersen (SMA)", "Onasemnogene abeparvovec (SMA)", "Risdiplam (SMA)", "IVIG (Guillain–Barré / neuroimmune)", "Methylprednisolone (IV pulse)", "Pyridostigmine"],
  "Psychiatry / behaviour / sleep": ["Methylphenidate", "Lisdexamfetamine", "Dexamfetamine", "Atomoxetine", "Guanfacine", "Clonidine", "Melatonin", "Risperidone", "Aripiprazole", "Quetiapine", "Olanzapine", "Clozapine", "Fluoxetine", "Sertraline", "Escitalopram", "Fluvoxamine", "Lithium", "Hydroxyzine (anxiety)", "Cognitive behavioural therapy", "Parent training / behavioural therapy"],
  "Endocrinology / diabetes / growth": ["Insulin (rapid-acting)", "Insulin (long-acting)", "Insulin (soluble, IV infusion)", "Insulin pump (CSII)", "Metformin", "Glibenclamide", "GLP-1 agonist (liraglutide / semaglutide)", "Glucagon (hypoglycaemia rescue)", "Dextrose / glucose gel", "Diazoxide", "Somatropin (growth hormone)", "Somatrogon / long-acting GH", "Mecasermin (IGF-1)", "Levothyroxine", "Liothyronine", "Carbimazole / methimazole", "Propylthiouracil", "Propranolol (thyrotoxicosis)", "Hydrocortisone", "Fludrocortisone", "Sodium chloride supplements (salt-wasting CAH)", "Dexamethasone", "Leuprorelin (GnRH analogue)", "Triptorelin (GnRH analogue)", "Testosterone", "Estradiol", "Ethinylestradiol / combined OCP", "Medroxyprogesterone", "Oxandrolone", "Letrozole / anastrozole", "Desmopressin (diabetes insipidus)", "Cinacalcet", "Calcitriol", "Burosumab (XLH)", "Phosphate supplements", "Bisphosphonate (pamidronate / zoledronate)", "Octreotide (hyperinsulinism)"],
  "Haematology / anticoagulation": ["Ferrous sulfate", "Ferrous fumarate", "Iron polymaltose", "Iron sucrose (IV)", "Ferric carboxymaltose (IV)", "Folic acid", "Vitamin B12 (hydroxocobalamin)", "Hydroxyurea (hydroxycarbamide)", "Penicillin V prophylaxis (sickle cell / asplenia)", "Deferasirox", "Deferoxamine", "Deferiprone", "Packed red cell transfusion", "Platelet transfusion", "Fresh frozen plasma", "Cryoprecipitate", "Factor VIII concentrate", "Factor IX concentrate", "Eptacog alfa (factor VIIa)", "Emicizumab", "Desmopressin (von Willebrand / haemophilia A)", "Tranexamic acid", "Vitamin K (phytomenadione)", "Enoxaparin", "Unfractionated heparin", "Warfarin", "Rivaroxaban", "Dabigatran", "IVIG (ITP)", "Anti-D immunoglobulin", "Eltrombopag", "Romiplostim", "Filgrastim (G-CSF)", "Pegfilgrastim"],
  "Oncology / immunosuppression": ["Vincristine", "Vinblastine", "Dasatinib", "Nilotinib", "Bosutinib", "Methotrexate", "Mercaptopurine", "Asparaginase / pegaspargase", "Cytarabine", "Daunorubicin / doxorubicin", "Cyclophosphamide", "Ifosfamide", "Etoposide", "Carboplatin", "Bleomycin", "Irinotecan", "Topotecan", "Bevacizumab", "Cisplatin", "Dexamethasone (chemotherapy)", "Imatinib", "Rituximab", "Blinatumomab", "Tacrolimus", "Ciclosporin", "Mycophenolate mofetil", "Sirolimus", "Everolimus", "Basiliximab", "Antithymocyte globulin (rabbit)", "Co-trimoxazole (PJP prophylaxis)", "Ondansetron (chemotherapy nausea)", "Granisetron", "Aprepitant", "Mesna", "Allopurinol (tumour lysis)", "Rasburicase", "Leucovorin (folinic acid) rescue"],
  "Immunology / rheumatology": ["IVIG (immunoglobulin replacement / Kawasaki)", "Subcutaneous immunoglobulin (SCIG)", "Aspirin (Kawasaki)", "Prednisolone", "Methylprednisolone (IV pulse)", "Methotrexate", "Hydroxychloroquine", "Sulfasalazine", "Leflunomide", "Etanercept", "Adalimumab", "Infliximab", "Tocilizumab", "Ustekinumab", "Secukinumab", "Ixekizumab", "Anakinra", "Canakinumab", "Abatacept", "Belimumab", "Colchicine", "Naproxen", "Intra-articular triamcinolone", "C1-esterase inhibitor", "Berotralstat", "Co-trimoxazole prophylaxis (immunodeficiency)", "Azithromycin prophylaxis"],
  "Dermatology": ["Emollient", "Hydrocortisone 1% cream", "Clobetasone butyrate", "Betamethasone valerate", "Hydrocortisone butyrate", "Clobetasol propionate", "Acitretin", "Mometasone furoate (topical)", "Tacrolimus ointment", "Abrocitinib", "Tralokinumab", "Pimecrolimus cream", "Crisaborole", "Dupilumab (atopic dermatitis)", "Wet wraps", "Zinc oxide (nappy rash)", "Clotrimazole cream", "Ketoconazole shampoo", "Permethrin 5%", "Malathion / dimeticone (head lice)", "Benzoyl peroxide", "Adapalene", "Adapalene–benzoyl peroxide", "Clindamycin–tretinoin", "Erythromycin–retinoid gel", "Topical clindamycin", "Isotretinoin", "Propranolol (infantile haemangioma)", "Timolol gel (haemangioma)", "Calcipotriol", "Calcipotriol–betamethasone", "Imiquimod", "Podophyllotoxin", "Silver sulfadiazine", "Coal tar", "Amorolfine", "Dithranol", "Tretinoin (topical)", "Erythromycin (topical)", "Urea (topical)", "Salicylic acid (warts)", "Cryotherapy"],
  "Ophthalmology / ENT": ["Chloramphenicol eye drops", "Vancomycin eye drops (fortified)", "Ceftazidime eye drops (fortified)", "Natamycin eye drops", "Gentamicin eye drops", "Tropicamide", "Phenylephrine eye drops", "Lidocaine / fluorescein", "Tobramycin eye drops", "Moxifloxacin eye drops", "Ciprofloxacin eye drops", "Levofloxacin eye drops", "Tobramycin–dexamethasone eye drops", "Travoprost", "Dorzolamide–timolol", "Fusidic acid eye drops", "Olopatadine eye drops", "Atropine eye drops (amblyopia / myopia)", "Cyclopentolate", "Prednisolone eye drops", "Artificial tears", "Timolol eye drops (glaucoma)", "Latanoprost", "Brimonidine", "Proxymetacaine", "Fluorescein (eye)", "Sodium chloride 5% eye drops", "Betamethasone ear drops", "Acetic acid ear spray", "Ciprofloxacin ear drops", "Ofloxacin ear drops", "Ciprofloxacin–dexamethasone ear drops", "Olive oil / sodium bicarbonate ear drops", "Xylometazoline / oxymetazoline nasal drops", "Saline nasal drops", "Nasal steroid spray", "Grommets (tympanostomy tubes)", "Adenotonsillectomy"],
  "Adolescent health / contraception": ["Ulipristal acetate (emergency contraception)", "Levonorgestrel (emergency contraception)", "Combined oral contraceptive", "Progestogen-only pill", "Medroxyprogesterone acetate (depot)", "Etonogestrel implant", "Levonorgestrel intrauterine system", "Norethisterone (menstrual disorders)", "Tranexamic acid (heavy menstrual bleeding)", "Mefenamic acid (dysmenorrhoea)", "HPV vaccine (catch-up)", "DTaP/IPV-containing vaccines", "Influenza vaccine (live, intranasal)", "Meningococcal group B vaccine", "Meningococcal ACWY vaccine", "Rotavirus vaccine", "Varicella vaccine", "Hepatitis B vaccine", "Pneumococcal conjugate vaccine", "Hexavalent vaccine (DTaP/IPV/Hib/HepB)"],
  "Neonatology": ["Vitamin K (phytomenadione) at birth", "Caffeine citrate", "Surfactant", "Ampicillin + gentamicin (early-onset sepsis)", "Cefotaxime", "Phototherapy", "Exchange transfusion", "IVIG (haemolytic disease)", "Dextrose 10%", "Parenteral nutrition", "Human milk fortifier", "Preterm formula", "Donor breast milk", "Iron supplement (preterm)", "Vitamin D (preterm)", "Multivitamin (preterm)", "Morphine (neonatal abstinence)", "Phenobarbital", "Indometacin / ibuprofen / paracetamol (PDA)", "Alprostadil (duct-dependent CHD)", "Inhaled nitric oxide", "Erythromycin eye ointment", "Hepatitis B immunoglobulin", "Nystatin prophylaxis", "Probiotics (preterm)", "Therapeutic hypothermia"],
  "Nutrition / vitamins / fluids": ["Vitamin D (cholecalciferol)", "Ergocalciferol", "Calcium carbonate", "Calcium gluconate", "Iron supplement", "Zinc", "Vitamin A", "Vitamin B complex", "Thiamine", "Vitamin C", "Folic acid", "Multivitamin", "Magnesium", "Phosphate", "Potassium chloride", "Sodium chloride", "Oral nutritional supplement", "Energy-dense infant formula", "Extensively hydrolysed formula", "Amino-acid formula", "Lactose-free formula", "Thickened / anti-reflux formula", "RUTF (ready-to-use therapeutic food)", "F-75 / F-100 therapeutic milk", "Nasogastric feeding", "Gastrostomy feeding", "Parenteral nutrition", "0.9% sodium chloride (IV)", "Plasma-Lyte / Hartmann's", "0.9% saline + 5% dextrose (maintenance)", "Dextrose 10%", "Dietitian review"],
  "Emergency / sedation / anaesthesia": ["Adrenaline (epinephrine)", "Atropine", "Amiodarone", "Adenosine", "Calcium chloride / gluconate", "Sodium bicarbonate", "Dextrose 10% bolus", "0.9% saline bolus", "Midazolam", "Ketamine", "Propofol", "Chloral hydrate", "Dexmedetomidine", "Morphine", "Fentanyl", "Naloxone", "Remifentanil", "Sufentanil", "Hydromorphone", "Etomidate", "Haloperidol", "Flumazenil", "Rocuronium", "Cisatracurium", "Vecuronium", "Atracurium", "Sugammadex", "Neostigmine", "Suxamethonium", "Hydrocortisone (adrenal crisis)", "Mannitol", "Hypertonic saline 3%", "Hypertonic saline 23.4%", "Salbutamol (hyperkalaemia)", "Insulin + dextrose (hyperkalaemia)", "Oxygen", "High-flow nasal cannula", "CPAP / non-invasive ventilation"],
  "Metabolic / genetic": ["Sodium benzoate", "Sodium phenylacetate–sodium benzoate (IV, acute hyperammonaemia)", "Sodium phenylbutyrate", "Carglumic acid", "Arginine", "Citrulline", "Triheptanoin", "L-carnitine", "Biotin", "Hydroxocobalamin (methylmalonic acidaemia)", "Sapropterin (PKU)", "Phenylalanine-free formula", "Galactose-free diet", "Uncooked cornstarch (GSD)", "Enzyme replacement therapy (MPS / Pompe / Gaucher / Fabry)", "Asfotase alfa", "Elosulfase alfa", "Agalsidase beta", "Imiglucerase", "Velaglucerase alfa", "Taliglucerase alfa", "Laronidase", "Galsulfase", "Nitisinone (tyrosinaemia)", "Givosiran", "Lumasiran", "Chenodeoxycholic acid", "Idursulfase", "Metabolic protein substitutes", "Cysteamine (cystinosis)", "Penicillamine / zinc (Wilson disease)", "Trientine", "Coenzyme Q10", "Riboflavin", "Ketogenic diet (GLUT1)", "Betaine (homocystinuria)"],
  "Toxicology / antidotes": ["Activated charcoal", "Acetylcysteine (paracetamol)", "Naloxone", "Flumazenil", "Atropine / pralidoxime (organophosphate)", "Deferoxamine (iron)", "Fomepizole / ethanol", "Digoxin-specific antibody", "Lipid emulsion 20% (local anaesthetic toxicity)", "Insulin high-dose (beta-blocker / CCB overdose)", "Glucagon (beta-blocker)", "Calcium (calcium-channel blocker)", "Octreotide (sulfonylurea)", "Sodium bicarbonate (tricyclic)", "Physostigmine", "Methylene blue", "Hydroxocobalamin (cyanide)", "Dimercaprol / DMSA / EDTA (lead)", "Antivenom", "Vitamin K (warfarin)", "Protamine (heparin)", "Prothrombin complex concentrate", "Fibrinogen concentrate", "Von Willebrand factor concentrate", "Andexanet alfa", "Aminocaproic acid", "Idarucizumab (dabigatran)"],
  "Immunisation-related (non-routine)": ["Tetanus immunoglobulin", "Rabies immunoglobulin", "Varicella-zoster immunoglobulin", "Hepatitis B immunoglobulin", "Normal human immunoglobulin (measles / hepatitis A post-exposure)", "Palivizumab", "Nirsevimab"],
  "Non-drug therapies": ["Physiotherapy", "Occupational therapy", "Speech and language therapy", "Psychology / counselling", "Dietary advice", "Weight-management programme", "Sleep hygiene", "Bladder training / enuresis alarm", "Toilet training programme", "Orthotics / splints", "Hearing aids", "Glasses / patching", "Chest physiotherapy", "Home oxygen", "Home ventilation", "Early intervention programme", "Special educational support", "Social work referral", "Surgery (specify)"],
};
/** Every treatment name, de-duplicated, for searching across all areas. */
export const ALL_TREATMENTS = [...new Set(Object.values(TREATMENT_CATS).flat())].sort((a, b) => a.localeCompare(b));
